In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [33]:
df = pd.read_csv("C:/Users/JULIETH/Downloads/heart_cleveland_upload.csv")

In [45]:
df.head(30)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,condition
0,69,1,0,160,234,1,2,131,0,0.1,1,1,0,0
1,69,0,0,140,239,0,0,151,0,1.8,0,2,0,0
2,66,0,0,150,226,0,0,114,0,2.6,2,0,0,0
3,65,1,0,138,282,1,2,174,0,1.4,1,1,0,1
4,64,1,0,110,211,0,2,144,1,1.8,1,0,0,0
5,64,1,0,170,227,0,2,155,0,0.6,1,0,2,0
6,63,1,0,145,233,1,2,150,0,2.3,2,0,1,0
7,61,1,0,134,234,0,0,145,0,2.6,1,2,0,1
8,60,0,0,150,240,0,0,171,0,0.9,0,0,0,0
9,59,1,0,178,270,0,2,145,0,4.2,2,0,2,0
10,59,1,0,170,288,0,2,159,0,0.2,1,0,2,1
11,59,1,0,160,273,0,2,125,0,0.0,0,0,0,1
12,59,1,0,134,204,0,0,162,0,0.8,0,2,0,1
13,58,0,0,150,283,1,2,162,0,1.0,0,0,0,0
14,56,1,0,120,193,0,2,162,0,1.9,1,0,2,0
15,52,1,0,118,186,0,2,190,0,0.0,1,0,1,0
16,52,1,0,152,298,1,0,178,0,1.2,1,0,2,0
17,51,1,0,125,213,0,2,125,1,1.4,0,1,0,0
18,45,1,0,110,264,0,0,132,0,1.2,1,0,2,1
19,42,1,0,148,244,0,2,178,0,0.8,0,2,0,0
20,40,1,0,140,199,0,0,178,1,1.4,0,0,2,0
21,38,1,0,120,231,0,0,182,1,3.8,1,0,2,1
22,34,1,0,118,182,0,2,174,0,0.0,0,0,0,0
23,74,0,1,120,269,0,2,121,1,0.2,0,1,0,0
24,71,0,1,160,302,0,0,162,0,0.4,0,2,0,0
25,70,1,1,156,245,0,2,143,0,0.0,0,0,0,0
26,66,1,1,160,246,0,0,120,1,0.0,1,3,1,1
27,63,0,1,140,195,0,0,179,0,0.0,0,2,0,0
28,62,1,1,120,281,0,2,103,0,1.4,1,1,2,1
29,62,1,1,128,208,1,2,140,0,0.0,0,0,0,0

In [47]:
df.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,condition
count,297.000000,297.000000,297.000000,297.000000,297.000000,297.000000,297.000000,297.000000,297.000000,297.000000,297.000000,297.000000,297.000000,297.000000
mean,54.542088,0.676768,2.158249,131.693603,247.350168,0.144781,0.996633,149.599327,0.326599,1.055556,0.602694,0.676768,0.835017,0.461279
std,9.049736,0.468500,0.964859,17.762806,51.997583,0.352474,0.994914,22.941562,0.469761,1.166123,0.618187,0.938965,0.956690,0.499340
min,29.000000,0.000000,0.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,48.000000,0.000000,2.000000,120.000000,211.000000,0.000000,0.000000,133.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,56.000000,1.000000,2.000000,130.000000,243.000000,0.000000,1.000000,153.000000,0.000000,0.800000,1.000000,0.000000,0.000000,0.000000
75%,61.000000,1.000000,3.000000,140.000000,276.000000,0.000000,2.000000,166.000000,1.000000,1.600000,1.000000,1.000000,2.000000,1.000000
max,77.000000,1.000000,3.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,3.000000,2.000000,1.000000